name: Tests
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/tablero_front:latest --tag islasgeci/tablero_front:${GITHUB_SHA:0:4} .
    - name: Corre contenedor
      run: make --makefile=build/Makefile up
    - name: Verifica el formato
      run: make --makefile=build/Makefile check
    - name: Checa estado del servicio
      run: make --makefile=build/Makefile check_status
    - name: Corre pruebas
      run: make --makefile=build/Makefile tests
    - name: Evalúa resistencia a mutaciones
      run: make --makefile=build/Makefile mutants
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/tablero_front:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/tablero_front:${GITHUB_SHA:0:4}
